exports.seed = function(knex) {
  const vendors = [
    {
      admin_id: 2,
      name: "Scott’s Tots",
      description: "The best darn tator tots in the south. We also have popcorn and lemonade.",
      items: ['Popcorn', 'Lemonade', 'Tator Tots'],
      electricity: true,
      ventilation: false,
      loud: false,
      other_special: null,
      email: "scottstots@gmail.com",
      phone: "337-555-7583",
      website: "scottstots.com",
      facebook: "facebook.com/scottstots",
      instagram: "instagram.com/scottstots",
      twitter: "twitter.com/scottstots"
    },
    {
      admin_id: 1,
      name: "Red, White, & Blooms",
      // description: "",
      items: ['Flowers'],
      electricity: true,
      ventilation: false,
      loud: false,
      other_special: null,
      email: "email@email.com",
      phone: "555-555-5555",
    },
    {
      admin_id: 1,
      name: "Mr. Beep Beep's Herbs",
      // description: "",
      items: ['Herbs'],
      electricity: true,
      ventilation: false,
      loud: false,
      other_special: null,
      email: "email@email.com",
      phone: "555-555-5555",
    },
    {
      admin_id: 1,
      name: "McMuffins",
      // description: "",
      items: ['Muffins'],
      electricity: true,
      ventilation: true,
      loud: false,
      other_special: null,
      email: "email@email.com",
      phone: "555-555-5555",
    },
    {
      admin_id: 1,
      name: "German Goods",
      // description: "",
      items: ['Lederhosen'],
      electricity: true,
      ventilation: false,
      loud: false,
      other_special: null,
      email: "email@email.com",
      phone: "555-555-5555",
    },
    {
      admin_id: 1,
      name: "Doggy Treats",
      // description: "",
      items: ['Doggy Treats'],
      electricity: true,
      ventilation: false,
      loud: false,
      other_special: null,
      email: "email@email.com",
      phone: "555-555-5555",
    },
    {
      admin_id: 1,
      name: "Creole Tomatoes",
      // description: "",
      items: ['Tomatoes'],
      electricity: true,
      ventilation: false,
      loud: false,
      other_special: null,
      email: "email@email.com",
      phone: "555-555-5555",
    },
    {
      admin_id: 1,
      name: "Big Boy Blueberries",
      // description: "",
      items: ['Blueberries'],
      electricity: true,
      ventilation: false,
      loud: false,
      other_special: null,
      email: "email@email.com",
      phone: "555-555-5555",
    },
    {
      admin_id: 1,
      name: "Aunt Debbie's Lil Peas",
      // description: "",
      items: ['Peas'],
      electricity: true,
      ventilation: false,
      loud: false,
      other_special: null,
      email: "email@email.com",
      phone: "555-555-5555",
    },
    {
      admin_id: 1,
      name: "Acadiana Slice Pie",
      // description: "",
      items: ['Pie'],
      electricity: true,
      ventilation: false,
      loud: false,
      other_special: null,
      email: "email@email.com",
      phone: "555-555-5555",
    }
  ]
  return (
    knex
      // Deletes ALL existing entries for users table
      .raw("TRUNCATE TABLE vendors RESTART IDENTITY CASCADE")
      .then(function() {
        return knex("vendors").insert(vendors);
      })
  );
};
